# -*- coding: utf-8 -*-
"""LandPricePrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EYdt56er1hu6uG83st-qSA1P4XdO4aj0

Import Library
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import math

"""Load Dataset"""

dataset = pd.read_csv('landpriceprediction.csv')

"""Load Summarize"""

print(dataset.shape)
print(dataset.head(5))
# print(dataset.describe())
# print(dataset.groupby('price').size())

"""Visualize Dataset"""

plt.xlabel('Land')
plt.ylabel('Price')
plt.scatter(dataset.land,dataset.price,color = 'red',marker = '*')

"""Segregate Dataset into Input X & Output Y"""

land = dataset.drop('price',axis='columns')
land

price = dataset.price
price

"""Training Dataset using Linear Regression"""

model = linear_model.LinearRegression()
model.fit(land,price)

"""Predicted Price for Land Sq.Feet of 1500"""

LandAreaInSqFeet = [[1500]]
PredictedModelResult = model.predict(LandAreaInSqFeet)
print(math.ceil(PredictedModelResult))

"""Let's Check is our model is Right?


Theory Calculation


Y = m * X + c (m is a coefficient and c is intercept)
"""

#Coeffient -m
m = model.coef_
print(m)

# Intercept -b
c = model.intercept_
print(c)

"""Y = mx + c
x is Independent variable -Input- area
"""

y = m*1500+ c
print("The Price of {0} Square Feet Land is : {1}".format(1500,y))

